"""empty message

Revision ID: 47785a524823
Revises: 0cac7bdf0f74
Create Date: 2024-04-06 21:01:44.165712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47785a524823'
down_revision: Union[str, None] = '0cac7bdf0f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'quantinity', new_column_name='quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'quantity', new_column_name='quantinity')
    # ### end Alembic commands ###
