"""Added created_at and updated_at fields to all tables

Revision ID: 0cac7bdf0f74
Revises: e65d3e986cca
Create Date: 2024-04-05 22:00:08.133779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cac7bdf0f74'
down_revision: Union[str, None] = 'e65d3e986cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('operation', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_operation_date'), 'operation', ['date'], unique=False)
    op.create_index(op.f('ix_operation_instrument_type'), 'operation', ['instrument_type'], unique=False)
    op.add_column('role', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    op.drop_index(op.f('ix_operation_instrument_type'), table_name='operation')
    op.drop_index(op.f('ix_operation_date'), table_name='operation')
    op.drop_column('operation', 'updated_at')
    op.drop_column('operation', 'created_at')
    # ### end Alembic commands ###
